export const skillList = [
  "- JavaScript",
  "- HTML",
  "- CSS",
  "- Bootstrap",
  "- TailWind",
  "- jQuery",
  "- React",
  "- Responsive Design",
  "- Git (Version Control System)",
  "- Webpack (Front-end build tool)",
  "- Jest",
  "- Chrome DevTools (Debugging tool)",
  "- RESTful APIs (API integration)",
  "- Progressive Web Apps (PWA) development",
  "- Node.js (Server-side programming language)",
  "- Express.js",
  "- MySQL",
  "- MongoDB",
  "- Sequelize",
  "- RESTful APIs",
];
